import BreadcrumbsLink from "@/components/BreadcrumbsLink";
import Header from "@/components/Header";
import ScrollToTop from "@/components/ScrollToTop";
import TabLink from "@/components/TabLink";
import { Card, CardBody, Divider, Tab, Tabs } from "@nextui-org/react";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="w-full  ">
            <Card className="min-h-screen w-full ">
                <Header />
                <Divider />
                <CardBody className="container w-full">
                    <div className="flex w-full items-center justify-between py-5">
                        <TabLink />
                        <BreadcrumbsLink />
                    </div>
                    {children}
                </CardBody>
            </Card>
            <ScrollToTop />
        </main >
    );
}
